return {
    {
		Name = "💼 Executives",
        Color = BrickColor.new("Black"),
        Rank = 20
    },
    {
		Name = "🔨 Developers",
		Color = BrickColor.new("Tr. Red"),
		Rank = 19
	},
	{
		Name = "👔 Management",
		Color = BrickColor.new("Pink"),
		Rank = 10
	},
	{
		Name = "Staff",
		Color = BrickColor.new("Light purple"),
		Rank = 4
    },
    {
		Name = "Customers",
        Color = BrickColor.new("Grey"),
        AutoAssignable = true
    }
}