return setmetatable({
	["Sakura"] = {
		Tier = "Epic",
		Image = "rbxassetid://16386299039",
		CanBeSold = true,
	},

	["Macaron"] = {
		Tier = "Basic",
		Image = "rbxassetid://16348763106",
		CanBeSold = true,
	},
	["Popsicle"] = {
		Tier = "Basic",
		Image = "rbxassetid://16348763002",
		CanBeSold = true,
	},
	["Strawberry"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349044402",
		CanBeSold = true,
	},
	["Orange"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349044564",
		CanBeSold = true,
	},
	["Grapes"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349044744",
		CanBeSold = true,
	},
	["Cherry"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349044888",
		CanBeSold = true,
	},
	["Coffee"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349078366",
		CanBeSold = true,
	},
	["Cookie"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349099182",
		CanBeSold = true,
	},
	["Jelly"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349099020",
		CanBeSold = true,
	},
	["Mochis"] = {
		Tier = "Basic",
		Image = "rbxassetid://16349116522",
		CanBeSold = true,
	},
}, {
	__index = {

	}
})
