return {
    Promotions = [[How to get promoted?
<font face="DenkOne">In order to be promoted, you must reach a certain amount of Staff Points.</font>

How to get Staff Points?
<font face="DenkOne">Staff Points are earned by hard work. Specifically, creating orders, completing orders or cleaning spills will grant you points depending on the difficulty of the task.</font>

I have enough points. How do I get promoted?
<font face="DenkOne">Boba has an automatic promotion system that will promote you in the group once you reach the required points. You might have to rejoin the game in order for your rank to update.</font>

<u>STAFF POINTS MILESTONES</u>
300 Staff Points → Barista
600 Staff Points → Senior Barista
10,000 Staff Points → Kitchen Leader

How to get promoted past Kitchen Leader?
<font face="DenkOne">We carefully pick who we promote past this rank, since Medium Ranks have access to administrative commands. In order to be eligible for a Medium Rank, you must have at least 1000+ Staff Points.</font>

Want to get promoted faster?
<font face="DenkOne">Make sure to check out the shop for exclusive offers on Staff Points!</font>

Want to become a Kitchen Leader immediately and have the top perks?
<font face="DenkOne">Purchase the Kitchen Leader pass from the shop to be ranked instantly!</font>]],

    Recipes = [[Boba:
<font face="DenkOne">Clear Cup + Milk + Syrup + Blender + Tapioca + Lid</font>

Coffee:
<font face="DenkOne">Cup + Coffee Machine + <i>(Opt.) Ice </i> + <i>(Opt.) Sugar</i> + Lid</font>

Tea:
<font face="DenkOne">Cup + Hot Water + Tea Powder + Lid</font>

Iced Tea:
<font face="DenkOne">Clear Cup + Cold Water + Tea Powder + Ice Machine + Lid</font>

Hot Chocolate:
<font face="DenkOne">Mug + Milk + Hot Chocolate Powder</font>]],
}